master:
  adminPassword: 'stallion'
  resources:
    requests:
      cpu: "1000m"
      memory: "1024Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

  serviceType: 'LoadBalancer'

  jenkinsUriPrefix: "/jenkins"

  healthProbeLivenessInitialDelay: 180
  healthProbeReadinessInitialDelay: 150

  ingress:
    enabled: true
    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    apiVersion: "extensions/v1beta1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      ingress.bluemix.net/redirect-to-https: "True"
    # Set this path to jenkinsUriPrefix above or use annotations to rewrite path
    path: "/jenkins"
    # configures the hostname e.g. jenkins.example.com
    hostName: k8s-husky-sandbox.tor01.containers.appdomain.cloud
    tls:
      - secretName: k8s-husky-sandbox
        hosts:
          - k8s-husky-sandbox.tor01.containers.appdomain.cloud

  installPlugins:
    - kubernetes:1.16.0
    - workflow-job:2.32
    - workflow-aggregator:2.6
    - credentials-binding:1.19
    - git:3.10.0
    - blueocean:1.17.0

persistence:
  storageClass: ibmc-file-gold

serviceAccountAgent:
  create: true
  name: cicd-jenkins

agent:
  idleMinutes: 5